name: 'Run markdownlint with reviewdog'
description: 'Run markdownlint with reviewdog on pull requests.'
author: 'chick-p'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
  markdownlint_flags:
    description: "Options of markdownlint command. Default: '.'"
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.markdownlint_flags }}
branding:
  icon: 'alert-octagon'
  color: 'blue'
