name: reviewdog
on: [pull_request]
jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: markdownlint-github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          markdownlint_flags: "testdata/*"
      - name: markdownlint-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          markdownlint_flags: "testdata/*"
